[package]
name = "job"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
autumn = { path = "../../autumn" }
autumn-job = { path = "../../autumn-job" }
autumn-sqlx = { path = "../../autumn-sqlx", features = [
    "postgres",
    "with-chrono",
] }
tokio = { workspace = true }
anyhow = { workspace = true }
