[package]
name = "job"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
autumn-boot = { path = "../../autumn-boot" }
autumn-job = { path = "../../autumn-job" }
tokio = { workspace = true }
anyhow = { workspace = true }
