[package]
name = "web-middleware-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-sqlx = { path = "../../spring-sqlx" }
tokio = { workspace = true, features = ["full", "tracing"] }
tower = { workspace = true }
tower-http = { workspace = true }
anyhow = { workspace = true }
