[web]
port = 8000
graceful = true
[web.middlewares]
static = { enable = true }
compression = { enable = true }
logger = { enable = true }
catch_panic = { enable = true }
timeout_request = { enable = true, timeout = 30000 }

[sqlx]
uri = "postgres://postgres:xudjf23adj213@127.0.0.1:5432"
min_connections = 10

[logger]
enable = true
level = "info"
time_style = "local"
time_pattern = "%Y-%m-%d %H:%M:%S"
with_fields = [
    "thread_id",
    "thread_name",
    "file",
    "line_number",
    "internal_errors",
]

[logger.file]
enable = true

[custom]
user_info_detail = "hello custom config"
