[web]
port = 8000
[web.middlewares]
static = { enable = true }
compression = { enable = true }
logger = { enable = true }
catch_panic = { enable = true }
timeout_request = { enable = true, timeout = 30000 }

[sqlx]
uri = "postgres://postgres:xudjf23adj213@127.0.0.1:5432"
min_connections = 10

[logger]
enable = true
level = "info"

[logger.file]
enable = true

[custom]
user_info_detail = "hello custom config"