[package]
name = "redis"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
autumn-boot = { path = "../../autumn-boot" }
autumn-web = { path = "../../autumn-web" }
autumn-redis = { path = "../../autumn-redis" }
tokio = { workspace = true }
anyhow = { workspace = true }