[package]
name = "actuator"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
autumn = { path = "../../autumn" }
autumn-web = { path = "../../autumn-web" }
autumn-actuator = { path = "../../autumn-actuator" }
tokio = { workspace = true }
anyhow = { workspace = true }
