[package]
name = "mail"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
autumn = { path = "../../autumn" }
autumn-web = { path = "../../autumn-web" }
autumn-mail = { path = "../../autumn-mail" }
tokio = { workspace = true }
anyhow = { workspace = true }