[package]
name = "spring-job"
description = "rust microservice framework"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
spring-boot = { path = "../spring-boot", version = "0.0.9" }
tokio-cron-scheduler = { workspace = true, features = ["signal"] }
anyhow = { workspace = true }
tracing = { workspace = true, features = ["log"] }
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true }
inventory = { workspace = true }

[dev-dependencies]
spring-sqlx = { path = "../spring-sqlx", version = "0.0.9" }
