[package]
name = "spring"
description = "Rust microservice framework"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
spring-boot = { path = "../spring-boot", version = "0.0.8" }
spring-macros = { path = "../spring-macros", version = "0.0.8" }

[dev-dependencies]
spring-web = { path = "../spring-web", version = "0.0.8" }
tokio = { workspace = true, features = ["full"] }
