[package]
name = "spring"
description = "Rust microservice framework"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
spring-boot = { path = "../spring-boot", version = "0.0.7" }
spring-macros = { path = "../spring-macros", version = "0.0.7" }

[features]
default = []
