[package]
name = "spring"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
spring-boot = { path = "../spring-boot" }
spring-macros = { path = "../spring-macros" }

[features]
default = []
