[package]
name = "web"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
autumn = { path = "../../autumn" }
autumn-web = { path = "../../autumn-web" }
autumn-sqlx = { path = "../../autumn-sqlx", features = ["mysql"] }
tokio = { workspace = true }
anyhow = { workspace = true }
