[package]
name = "postgres-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-postgres = { path = "../../spring-postgres"}
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }