[package]
name = "autumn"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
autumn-boot = { path = "../autumn-boot" }
autumn-macros = { path = "../autumn-macros" }

[features]
default = []
