[package]
name = "spring-opentelemetry"
description = "rust microservice framework"
version = "0.2.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
spring = { path = "../spring", version = "0.2" }
serde = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true, features = ["log"] }
schemars = { workspace = true }

[dev-dependencies]
spring-web = { path = "../spring-web" }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry-stdout = { workspace = true }
opentelemetry-http = { workspace = true }
opentelemetry-appender-tracing = { workspace = true }
opentelemetry-jaeger-propagator = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-prometheus = { workspace = true }
opentelemetry-zipkin = { workspace = true }
opentelemetry-resource-detectors = { workspace = true }
tracing-opentelemetry = { workspace = true }
