[package]
name = "plugin-example"
version = "0.0.4"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring-boot = { path = "../../spring-boot" }
toml = { workspace = true, features = ["parse"], default-features = false }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
async-trait = { workspace = true }
