[package]
name = "plugin-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring-boot = { path = "../../spring-boot" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
