[package]
name = "mail-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-mail = { path = "../../spring-mail" }
tokio = { workspace = true }
anyhow = { workspace = true }
