[package]
name = "sea-orm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
autumn = { path = "../../autumn" }
autumn-web = { path = "../../autumn-web" }
autumn-sea-orm = { path = "../../autumn-sea-orm", features = ["postgres"] }
tokio = { workspace = true }
anyhow = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }