[package]
name = "opendal-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-opendal = { path = "../../spring-opendal", features = ["services-fs"] }
tokio = { workspace = true, features = ["full", "tracing"] }
