[package]
name = "web-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-sqlx = { path = "../../spring-sqlx", features = ["mysql"] }
tokio = { workspace = true, features = ["full", "tracing"] }
anyhow = { workspace = true }

# benchmark compare
axum = { workspace = true }
actix-web = "4"
ntex = { version = "2.0", features = ["tokio"] }