[package]
name = "web-example"
version = "0.0.4"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-sqlx = { path = "../../spring-sqlx", features = ["mysql"] }
tokio = { workspace = true }
anyhow = { workspace = true }
