[package]
name = "spring-web"
description = "rust microservice framework"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
http2 = ["axum/http2"]
multipart = ["axum/multipart"]
ws = ["axum/ws"]

[dependencies]
spring = { path = "../spring", version = "0.1.1" }
spring-macros = { path = "../spring-macros", version = "0.1.1" }
axum = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["full"] }
byte-unit = { workspace = true, features = ["serde"] }
schemars = { workspace = true }
inventory = { workspace = true }
