[package]
name = "job-example"
version = "0.0.4"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-job = { path = "../../spring-job" }
spring-sqlx = { path = "../../spring-sqlx", features = [
    "postgres",
    "with-chrono",
] }
tokio = { workspace = true }
anyhow = { workspace = true }
