name: Docs

on:
  push:
    branches: ["master"]
    paths:
      - "docs"
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      msg:
        required: false

jobs:
  build:
    name: zola deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: zbrox/zola-deploy-action
      uses: zbrox/zola-deploy-action@master
      env:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}